# Generated by Django 3.0.5 on 2020-04-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydata',
            name='country',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='state',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='state_code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
