# Generated by Django 3.0.5 on 2020-04-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200402_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydata',
            name='active_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='cases_today',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='critical_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='total_confirmed_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='total_death',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='total_recovered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='active_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='cases_today',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='critical_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='total_confirmed_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='total_death',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='total_recovered',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
