# Generated by Django 3.0.5 on 2020-04-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200402_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='state_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
